### ISSUE TITLE
Output messages for nested given, when, thens

### ISSUE THREAD

**Issue by robmunro** [tristanstraub/gwt#8]
It would be great to have message outputs for nested given, when, thens

eg. 
-      ✓ given a user is created
-      ✓ when a product is created
  -          ✓ when a product is duplicated
  -         ✓ when a product name is changed

**Comment by tristanstraub** [comment]
I'll take a look at this. The code needs a rewrite since it's not maintainable in its current state. I'll make sure this get's in.
